/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package milkman;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rakesh
 */
public class displayreportsingledate extends javax.swing.JInternalFrame {

    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    String reporttodispalay;
    Connection conn;
    String qry = "";
    int shiftid;
    private Date date = new Date();
    SimpleDateFormat mdy = new SimpleDateFormat("MM/dd/yyyy");
    SimpleDateFormat dmy = new SimpleDateFormat("dd/MM/yyyy");    
    private int[] grid;
    
    public displayreportsingledate(String reportname) throws SQLException {
        initComponents();
        reporttodispalay = reportname;
        if(conn!=null){
            conn.close();
        }
        conn = methods.getConnection();
        
        // producer group
        qry = "SELECT producergroup.ID, producergroup.grid" +
                " FROM producergroup;";
        PreparedStatement loadqry = conn.prepareStatement(qry);
        int i = 0;
        try (ResultSet rscombo = loadqry.executeQuery()) {
            grid = new int[30];
            cmbgroup.insertItemAt("ALL", i);
            grid[i] = 0;                
            while(rscombo.next()) {
                i++;
                cmbgroup.insertItemAt(rscombo.getString("grid"), i);
                grid[i] = rscombo.getInt("ID");
            }
        }
        cmbgroup.setSelectedIndex(0);
        
        conn = methods.getConnection();  
        dtpfromdate.setDate(date);   
        optmorning.setSelected(true);
        
        if ("Rojkird".equals(reporttodispalay)) {
            jLabel7.setVisible(false);
            optmorning.setVisible(false);
            optevening.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dtpfromdate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        optmorning = new javax.swing.JRadioButton();
        optevening = new javax.swing.JRadioButton();
        cmbgroup = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setTitle("तारखेप्रमाणे रिपोर्ट बघणे");

        jPanel1.setBackground(new java.awt.Color(113, 168, 168));

        jLabel5.setFont(new java.awt.Font("Mangal", 1, 24)); // NOI18N
        jLabel5.setText("तारखे प्रमाणे रिपोर्ट बघणे");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(113, 168, 168));

        jButton1.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jButton1.setText("रिपोर्ट बघणे");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jButton2.setText("बाहेर");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("दिनांक :");

        dtpfromdate.setFocusable(false);
        dtpfromdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("शिफ्ट :");

        optmorning.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(optmorning);
        optmorning.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        optmorning.setForeground(new java.awt.Color(51, 51, 255));
        optmorning.setText("सकाळ");
        optmorning.setFocusable(false);
        optmorning.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                optmorningStateChanged(evt);
            }
        });
        optmorning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmorningActionPerformed(evt);
            }
        });

        optevening.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(optevening);
        optevening.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        optevening.setForeground(new java.awt.Color(51, 51, 255));
        optevening.setText("संध्याकाळ");
        optevening.setFocusable(false);
        optevening.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opteveningStateChanged(evt);
            }
        });
        optevening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opteveningActionPerformed(evt);
            }
        });

        cmbgroup.setFont(new java.awt.Font("Mangal", 0, 12)); // NOI18N
        cmbgroup.setFocusable(false);
        cmbgroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbgroupItemStateChanged(evt);
            }
        });
        cmbgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgroupActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("उत्पादक ग्रुप :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optmorning, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(optevening))
                    .addComponent(cmbgroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dtpfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optmorning, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optevening, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cond_qry;
        switch (reporttodispalay) {
            case "Shift Report":
                if (cmbgroup.getSelectedItem()!="ALL") {
                    cond_qry = "mlkCollection.shift_id = "+ shiftid +" and mlkCollection.trn_date = #"+ mdy.format(dtpfromdate.getDate()) +"# and producergroupid = "+cmbgroup.getSelectedItem()+"";
                } else {
                    cond_qry = "mlkCollection.shift_id = "+ shiftid +" and mlkCollection.trn_date = #"+ mdy.format(dtpfromdate.getDate()) +"#";
                }
                try {
                    methods.displayreport("shiftreport", conn, cond_qry);
                } catch (SQLException ex) {
                    Logger.getLogger(milkcollection.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "reciept":
                if (cmbgroup.getSelectedItem()!="ALL") {
                    cond_qry = "mlkCollection.shift_id = "+ shiftid +" and mlkCollection.trn_date = #"+ mdy.format(dtpfromdate.getDate()) +"# and producergroupid = "+cmbgroup.getSelectedItem()+"";
                } else {
                    cond_qry = "mlkCollection.shift_id = "+ shiftid +" and mlkCollection.trn_date = #"+ mdy.format(dtpfromdate.getDate()) +"#";
                }
                try {
                    methods.displayreport("rptrecieptfullpage", conn, cond_qry); //rptmilkbillreciept
                } catch (SQLException ex) {            
                    Logger.getLogger(milkcollection.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "Rojkird":
                cond_qry = "dailytrn.trndate = #"+ mdy.format(dtpfromdate.getDate()) +"#";
                try {
                    methods.displayreport("rpt_rojkird", conn, cond_qry); //rptmilkbillreciept
                } catch (SQLException ex) {            
                    Logger.getLogger(milkcollection.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        if (conn!=null) {
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(displayreportdatecriteria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void optmorningStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_optmorningStateChanged
        if(optmorning.isSelected()==true){
            shiftid = 1;
        } else {
            shiftid = 2;
        }
    }//GEN-LAST:event_optmorningStateChanged

    private void optmorningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmorningActionPerformed
        
    }//GEN-LAST:event_optmorningActionPerformed

    private void opteveningStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opteveningStateChanged
        if(optevening.isSelected()==true){
            shiftid = 2;
        } else {
            shiftid = 1;
        }
        
    }//GEN-LAST:event_opteveningStateChanged

    private void opteveningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opteveningActionPerformed
        
    }//GEN-LAST:event_opteveningActionPerformed

    private void cmbgroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbgroupItemStateChanged
        
    }//GEN-LAST:event_cmbgroupItemStateChanged

    private void cmbgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgroupActionPerformed
        ////        if(cmbgroup.getItemCount() > 0 && framestate != 3 && framestate != 2) {
            ////            int prodid = getprodid();
            ////            txtproducerid.setText(""+prodid);
            ////        } else if (framestate == 3){
            ////            //displayrecord(4);
            ////        }
    }//GEN-LAST:event_cmbgroupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbgroup;
    private com.toedter.calendar.JDateChooser dtpfromdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton optevening;
    private javax.swing.JRadioButton optmorning;
    // End of variables declaration//GEN-END:variables
}
