
package milkman;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class jama extends javax.swing.JInternalFrame {

    
    private Connection conn;
    private ResultSet rs;
    private int framestate; // 1 : view mode 2: add mode 3 : edit mode
    private int[] khate2id;
    private int[] khate1id;
    private int[] pavatiprakarid;
    private int id;
    SimpleDateFormat dmy = new SimpleDateFormat("dd/MM/yyyy");
    PreparedStatement INSERT_QRY = null;
    int trntype;
    
    public jama(int trntype) {
        try {
            initComponents();
            String qry = "INSERT INTO dailytrn (trndate,voucherid,chalanno,accid,dramt,cramt,naration)"+
                           " VALUES (?,?,?,?,?,?,?)";
           
            this.trntype = trntype;
            if(conn!=null) {
                    conn.close();
                }
            conn = methods.getConnection();        
            INSERT_QRY = conn.prepareStatement(qry);
            
            framestate = 3;
            ED_BUTTONS(false, true);
            loadcombo();
            //dtpdate.setDate(methods.currdate);
            
            displayrecord(4);
            
            if (trntype==1) { // jamaa trandaction
                
                jLabel1.setText("व्यवहार : जमा");
                
            } else if (trntype==2) { // naave transaction
            
                jLabel1.setText("व्यवहार : नावे");
                
            }
            

            
        } catch (SQLException ex) {
            Logger.getLogger(jama.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        dtpdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbpavatiprakar = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtchalanno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbkhate1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbkhate2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtamount = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        lblpassunpass = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtparticular = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setTitle("व्यवहार जमा / नावे");

        jPanel1.setBackground(new java.awt.Color(113, 168, 168));

        jButton1.setBackground(new java.awt.Color(128, 157, 201));
        jButton1.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton1.setText("नवीन");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton2.setText("बदल");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton3.setText("डिलीट");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton4.setMnemonic('s');
        jButton4.setText("सेव्ह");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setBorderPainted(false);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton5.setText("शोधणे");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setBorderPainted(false);
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton6.setText("बंद");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.setBorderPainted(false);
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        btnprint.setText("प्रिंट");
        btnprint.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnprint.setBorderPainted(false);
        btnprint.setOpaque(false);
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(113, 168, 168));

        jButton7.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton7.setText("पहिला");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.setBorderPainted(false);
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton8.setText("आगोदर");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton8.setBorderPainted(false);
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton9.setText("पुढचा");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.setBorderPainted(false);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton10.setText("शेवटचा");
        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton10.setBorderPainted(false);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID :");

        txtid.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        dtpdate.setFocusable(false);
        dtpdate.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("दिनांक :");

        jLabel1.setBackground(new java.awt.Color(113, 168, 168));
        jLabel1.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("रोजकीर्द व्यवहार");
        jLabel1.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("पावती प्रकार :");

        cmbpavatiprakar.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N
        cmbpavatiprakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpavatiprakarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel5.setText("चलन क्र. :");

        txtchalanno.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("खाते १ :");

        cmbkhate1.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N
        cmbkhate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkhate1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("खाते २ :");

        cmbkhate2.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("रक्कम :");

        txtamount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtamount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtamount.setToolTipText("");
        txtamount.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N
        txtamount.setName(""); // NOI18N
        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("शेरा :");

        lblpassunpass.setBackground(new java.awt.Color(255, 204, 51));
        lblpassunpass.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        lblpassunpass.setForeground(new java.awt.Color(255, 0, 0));
        lblpassunpass.setText("पास / अनपास");
        lblpassunpass.setOpaque(true);

        txtparticular.setColumns(20);
        txtparticular.setRows(5);
        jScrollPane1.setViewportView(txtparticular);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbkhate2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbkhate1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpassunpass, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel3))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbpavatiprakar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtchalanno, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtchalanno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbpavatiprakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbkhate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbkhate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblpassunpass)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadcombo() {
        try {
            
            cmbkhate1.removeAll();
            cmbkhate2.removeAll();
            cmbpavatiprakar.removeAll();
            
            int i=0;
            
//            if(conn!=null) {
//                conn.close();
//            }
//            conn = methods.getConnection();
            ResultSet rscombo;
            String qry;
            qry = "";
            
            // खाते प्रकार
            qry = "SELECT account.ID, account.accname " +
                    "FROM account " +
                    "ORDER BY account.ID;";
            try (PreparedStatement loadqry = conn.prepareStatement(qry)) {
                rscombo = loadqry.executeQuery();
                khate1id = new int[200];
                khate2id = new int[200];
                
                while(rscombo.next()) {
                   String accname = rscombo.getString("accname");
                   int accid = rscombo.getInt("ID");
                   cmbkhate1.insertItemAt(accname, i);
                   cmbkhate2.insertItemAt(accname, i);
                   khate1id[i] = accid;
                   khate2id[i] = accid;
                   i++;
                }
                cmbkhate1.setSelectedIndex(-1);
                cmbkhate2.setSelectedIndex(-1);
                rscombo.close();
            }

            // Vaoucher Type
            qry = "SELECT vouchertype.ID, vouchertype.vtype " +
                    "FROM vouchertype;";
            try (PreparedStatement ratechartid = conn.prepareStatement(qry)) {
                rscombo = ratechartid.executeQuery();
                pavatiprakarid = new int[10];
                i = 0;
                while(rscombo.next()) {
                   cmbpavatiprakar.insertItemAt(rscombo.getString("vtype"), i);
                   pavatiprakarid[i] = rscombo.getInt("ID");
                   i++;
                }
                rscombo.close();
                cmbpavatiprakar.setSelectedIndex(0);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(jama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // method for geting
    public int getchalanno() {
        int cno = 0;
        try {
            String chalanqry = "SELECT Max(dailytrn.chalanno) AS MaxOfchalanno FROM dailytrn;";
            try (PreparedStatement stm = conn.prepareStatement(chalanqry)) {
                ResultSet rschno = stm.executeQuery();
                while (rschno.next()) {
                    cno = rschno.getInt("MaxOfchalanno");
                }
                cno = cno + 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(methods.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cno;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        framestate = 1;
        ED_BUTTONS(true, false);
        
        emptyctr();
        
        dtpdate.requestFocus();
//        getbankopnbal();
//        this.date = new Date();
//
//        dtpmtdate.setDate(date);
//        dtpfromdate.setDate(date);
//        dtptodate.setDate(date);
//        dtpbankwidhrawdate.setDate(date);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emptyctr() {
        txtid.setText("");
        txtchalanno.setText(""+getchalanno());
        txtparticular.setText("");
        dtpdate.setDate(methods.currdate);

        cmbkhate1.setSelectedIndex(-1);
        cmbkhate2.setSelectedIndex(-1);
        cmbpavatiprakar.setSelectedIndex(0);
        txtamount.setText("0.00");
    }

    private void ED_BUTTONS(boolean f1, boolean f2) {
        if(framestate==1 || framestate==2){
            txtchalanno.setEditable(f1);
            lblpassunpass.setVisible(f2);
        } else {
            txtchalanno.setEditable(f2);
            lblpassunpass.setVisible(f2);
        }
        
        txtparticular.setEditable(f1); // true
        
        cmbkhate1.setEnabled(f1);
        cmbkhate2.setEnabled(f1);
        cmbpavatiprakar.setEnabled(f1);
        dtpdate.setEnabled(f1);

        btnprint.setEnabled(f2);

        // buttoms
        jButton1.setEnabled(f2); //new false
        jButton2.setEnabled(f2); //edit false
        jButton3.setEnabled(f2); //delete false 
        jButton4.setEnabled(f1); //save true
        jButton5.setEnabled(f2); //search false 
        if(framestate==1 || framestate==2){
            jButton6.setEnabled(f1); //exit true
            jButton6.setText("मागे"); 
        }
        else {
            jButton6.setEnabled(f2); //exit true
            jButton6.setText("बंद"); 
        }
        jButton7.setEnabled(f2); //first
        jButton8.setEnabled(f2); //previouse
        jButton9.setEnabled(f2); //next
        jButton10.setEnabled(f2); //last
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "कृपया पोस्टिंग मधून एन्ट्री खोडून नवीन एन्ट्री करा...!!!", "Milkman -> Rojkird", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String msg = "रेकॉर्ड कायमचा काढून टाकणे?";
        int ans;
//        if(!txtid.getText().equals("")) {
//            ans = JOptionPane.showConfirmDialog(null, msg, title, JOptionPane.ERROR_MESSAGE);
//            if(ans == JOptionPane.YES_OPTION){
//                try {
//                    String deleteqry = "DELETE * FROM moneytransfer WHERE ID = " + txtid.getText()+";";
//                    PreparedStatement DELETE_QRY = conn.prepareStatement(deleteqry);
//                    DELETE_QRY.execute();
//                    JOptionPane.showMessageDialog(null, "रेकॉर्ड काढून टाकण्यात आला आहे.", title, JOptionPane.INFORMATION_MESSAGE);
//                    emptyctr();
//                    //displayrecord(4);
//                } catch (SQLException ex) {
//                    Logger.getLogger(sangh.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "रेकॉर्ड नाही..!!", title, JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // Insert new Record
            if(framestate==1){
                if (trntype==1) { // jamaa
                    for (int i=0;i<2;i++) {
                        INSERT_QRY.setString(1, ""+dmy.format(dtpdate.getDate()));
                        INSERT_QRY.setInt(2, pavatiprakarid[cmbpavatiprakar.getSelectedIndex()]);
                        INSERT_QRY.setDouble(3, Integer.parseInt(txtchalanno.getText()));
                        if (i==0) { // jamaa
                            INSERT_QRY.setDouble(4, khate1id[cmbkhate1.getSelectedIndex()]);
                            INSERT_QRY.setString(5, txtamount.getText()); // dr amount
                            INSERT_QRY.setDouble(6, 0); // cr amount
                        } else { // nave
                            INSERT_QRY.setDouble(4, khate2id[cmbkhate2.getSelectedIndex()]); 
                            INSERT_QRY.setDouble(5, 0); // dr amount
                            INSERT_QRY.setString(6, txtamount.getText()); // cr amount
                        }

                        INSERT_QRY.setString(7, txtparticular.getText());

                        INSERT_QRY.execute();
                    }
                } else if (trntype==2) {
                    for (int i=0;i<2;i++) {
                        INSERT_QRY.setString(1, ""+dmy.format(dtpdate.getDate()));
                        INSERT_QRY.setInt(2, pavatiprakarid[cmbpavatiprakar.getSelectedIndex()]);
                        INSERT_QRY.setDouble(3, Integer.parseInt(txtchalanno.getText()));
                        if (i==0) { // naave
                            INSERT_QRY.setDouble(4, khate1id[cmbkhate1.getSelectedIndex()]);
                            INSERT_QRY.setString(6, txtamount.getText()); // dr amount
                            INSERT_QRY.setDouble(5, 0); // cr amount
                        } else { // jamaa
                            INSERT_QRY.setDouble(4, khate2id[cmbkhate2.getSelectedIndex()]); 
                            INSERT_QRY.setDouble(6, 0); // dr amount
                            INSERT_QRY.setString(5, txtamount.getText()); // cr amount
                        }

                        INSERT_QRY.setString(7, txtparticular.getText());

                        INSERT_QRY.execute();
                    }                    
                }
            } else if(framestate==2){ // Update Existing record
               
            }
            String msg = "रेकॉर्ड सेव्ह झाला.";
            JOptionPane.showMessageDialog(null, msg, title, JOptionPane.INFORMATION_MESSAGE);
            framestate=3;
            ED_BUTTONS(false, true);
//            displayrecord(4);
        } catch (SQLException ex) {
            Logger.getLogger(sangh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void displayrecord(int flag) {
        if(framestate==3){
            try {
//                if(conn!=null){
//                    conn.close();
//                }
//                conn = methods.getConnection();
                String qry = null;
//                if (trntype==1) { // jamaa
                    if(flag==4){
                       qry = "SELECT * FROM dailytrn WHERE chalanno=(SELECT max(chalanno) FROM dailytrn);";
                    }
                    if(flag==1){
                       qry = "SELECT * FROM dailytrn WHERE chalanno=(SELECT min(chalanno) FROM dailytrn);";
                    }
                    if(flag==2){
                       qry = "SELECT * FROM dailytrn WHERE chalanno<"+txtchalanno.getText()+" ORDER BY chalanno DESC;";
                    }
                    if(flag==3){
                       qry = "SELECT * FROM dailytrn WHERE chalanno>"+txtchalanno.getText()+" ORDER BY chalanno;";
                    }                
                    if(flag==5){
                       qry = "SELECT * FROM dailytrn WHERE chalanno="+txtchalanno.getText()+";";
                    }                                
//                } else if (trntype==2){ // 
//                    
//                }
                PreparedStatement selectqry = conn.prepareStatement(qry);
                rs = selectqry.executeQuery();
                int i = 0;
                //emptyctr();
                while(rs.next()){

                    txtid.setText(rs.getString("ID"));
                    txtchalanno.setText(""+rs.getInt("chalanno"));
                    dtpdate.setDate(rs.getDate("trndate"));
                    int vtype = rs.getInt("voucherid");
                    for (int j=0;j<cmbpavatiprakar.getItemCount();j++) {
                        if (pavatiprakarid[j]==vtype){
                            cmbpavatiprakar.setSelectedIndex(j);
                            break;
                        }
                    }
                    int acid = rs.getInt("accid");
                    if(i==0) {
                        for (int j=0;j<cmbkhate1.getItemCount();j++) {
                            if (khate1id[j]==acid){
                                cmbkhate1.setSelectedIndex(j);
                                break;
                            }
                        }
                    } else if(i==1) {
                        for (int j=0;j<cmbkhate2.getItemCount();j++) {
                            if (khate2id[j]==acid){
                                cmbkhate2.setSelectedIndex(j);
                                break;
                            }
                        }
                    }
                    if (trntype==1) {
                        txtamount.setText(rs.getString("cramt"));
                    } else if (trntype==2){
                        txtamount.setText(rs.getString("dramt"));
                    }
                    txtparticular.setText(rs.getString("naration"));
                    if (rs.getBoolean("posting")==true) {
                        lblpassunpass.setText("पास");
                    } else {
                        lblpassunpass.setText("अनपास");
                    }

                    i++;
                    if (i>1) break;
                }
                rs.close();
//                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(producer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        displayrecord(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(framestate==3){
            if (conn!=null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(moneytransfer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            dispose();
        }
        else {
            framestate = 3;
            ED_BUTTONS(false, true);
//            displayrecord(4);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        //        try {
            //            methods.displayreport("Producerlist", conn);
            //        } catch (SQLException ex) { //JRException |
            //            Logger.getLogger(sangh.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(1);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(2);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(3);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(4);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    private void cmbpavatiprakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpavatiprakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbpavatiprakarActionPerformed

    private void cmbkhate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkhate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkhate1ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprint;
    private javax.swing.JComboBox cmbkhate1;
    private javax.swing.JComboBox cmbkhate2;
    private javax.swing.JComboBox cmbpavatiprakar;
    private com.toedter.calendar.JDateChooser dtpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpassunpass;
    private javax.swing.JFormattedTextField txtamount;
    private javax.swing.JTextField txtchalanno;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextArea txtparticular;
    // End of variables declaration//GEN-END:variables
}
