/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package milkman;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rakesh
 */
public class moneytransfer extends javax.swing.JInternalFrame {

    private Date date;
    SimpleDateFormat mdy = new SimpleDateFormat("MM/dd/yyyy");
    SimpleDateFormat dmy = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss a");
    DecimalFormat onedf = new DecimalFormat("#.0");
    DecimalFormat twodf = new DecimalFormat("#0.00");
    Connection conn;
    PreparedStatement INSERT_QRY;
    String qry = "";
    int framemode;
    private int prod_ratechartno;
    
    public moneytransfer() {
        try {
            this.date = new Date();
            initComponents();
            
            dtpmtdate.setDate(date);
            dtpfromdate.setDate(date);
            dtptodate.setDate(date);
            dtpbankwidhrawdate.setDate(date);
            
            if(conn!=null){
                conn.close();
            }
            conn = methods.getConnection();
            
            // Prepate statement for inserting record
            qry = "INSERT INTO moneytransfer (mtdate,fromdate,todate,snaghcode,totalmilksend,totalmilkamt,"+
                    "sharededuct,rebatededuct,otherdeduct,totalamtrecieved,bankcurrentbal,bankwithdrawamt,"+
                    "bankbalance,anamatrecieved,netpayment,anamatpaid,totalexpences,cashinhand,profitorloss,"+
                    "totalcomm,banckwidhrawdate,shetkaribachat) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            INSERT_QRY = conn.prepareStatement(qry);
            
            this.framemode = 3; // add mode
            
            clearscreen();
            ED_BUTTONS(false, true);
            displayrecord(4);           
            
        } catch (SQLException ex) {
            Logger.getLogger(moneytransfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ED_BUTTONS(boolean f1, boolean f2) {
      
        dtpmtdate.setEnabled(f1); // true
        dtpfromdate.setEnabled(f1); // true
        dtptodate.setEnabled(f1); // true
        dtpbankwidhrawdate.setEnabled(f1); // true
        txtsanghid.setEditable(f1);
        txtsanghname.setEditable(f1);
        txtsharededuct.setEditable(f1);
        txtotherdeduct.setEditable(f1);
        txtbankwithdrawamt.setEditable(f1);
        txtanamatrecieved.setEditable(f1);
        txtanamatpaid.setEditable(f1);
        txtexpences.setEditable(f1);
        
        btnprint.setEnabled(f2);

        // buttoms
        jButton1.setEnabled(f2); //new false
        jButton2.setEnabled(f2); //edit false
        jButton3.setEnabled(f2); //delete false 
        jButton4.setEnabled(f1); //save true
        jButton5.setEnabled(f2); //search false 
        if(framemode==1 || framemode==2){
            jButton6.setEnabled(f1); //exit true
            jButton6.setText("मागे"); 
        }
        else {
            jButton6.setEnabled(f2); //exit true
            jButton6.setText("बंद"); 
        }
        jButton7.setEnabled(f2); //first
        jButton8.setEnabled(f2); //previouse
        jButton9.setEnabled(f2); //next
        jButton10.setEnabled(f2); //last
    }
    
    private void clearscreen() {
        txtid.setText(null);
        txtsanghid.setText(null);
        txtsanghname.setText(null);
        txttotalmilksend.setText("0.0");
        txttotalmilksendamt.setText("0.0");
        txtsharededuct.setText("0.0");
        txttotalrebatededuct.setText("0.0");
        txtotherdeduct.setText("0.0");
        txttotalamountrecived.setText("0.0");
        txtcurrentbankbalance.setText("0.0");
        txtbankwithdrawamt.setText("0.0");
        txtbankbalance.setText("0.0");
        txtanamatrecieved.setText("0.0");
        txtpaymentdetail.setText("0.0");
        txtbachat.setText("0.0");
        txtanamatpaid.setText("0.0");
        txtexpences.setText("0.0");
        txtcashinhand.setText("0.0");
        txtprofitloss.setText("0.0");
        txttotalcommisiion.setText("0.0");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtsanghid = new javax.swing.JTextField();
        txtsanghname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dtpmtdate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dtpfromdate = new com.toedter.calendar.JDateChooser();
        dtptodate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtcurrentbankbalance = new javax.swing.JTextField();
        txtbankwithdrawamt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtbankbalance = new javax.swing.JTextField();
        dtpbankwidhrawdate = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txttotalmilksend = new javax.swing.JTextField();
        txttotalmilksendamt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtsharededuct = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txttotalrebatededuct = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtotherdeduct = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txttotalamountrecived = new javax.swing.JTextField();
        txttotalcommisiion = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtanamatrecieved = new javax.swing.JTextField();
        txtpaymentdetail = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtanamatpaid = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtexpences = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtcashinhand = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtprofitloss = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtbachat = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setTitle("मनी ट्रान्स्फर");

        jPanel1.setBackground(new java.awt.Color(113, 168, 168));

        jButton1.setBackground(new java.awt.Color(128, 157, 201));
        jButton1.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton1.setText("नवीन");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton2.setText("बदल");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton3.setText("डिलीट");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton4.setMnemonic('s');
        jButton4.setText("सेव्ह");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setBorderPainted(false);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton5.setText("शोधणे");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setBorderPainted(false);
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton6.setText("बंद");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.setBorderPainted(false);
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        btnprint.setText("प्रिंट");
        btnprint.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnprint.setBorderPainted(false);
        btnprint.setOpaque(false);
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(113, 168, 168));

        jButton7.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton7.setText("पहिला");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.setBorderPainted(false);
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton8.setText("आगोदर");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton8.setBorderPainted(false);
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton9.setText("पुढचा");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.setBorderPainted(false);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jButton10.setText("शेवटचा");
        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton10.setBorderPainted(false);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel1.setText("संघ कोड :");

        txtsanghid.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtsanghid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsanghid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsanghidActionPerformed(evt);
            }
        });
        txtsanghid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsanghidKeyReleased(evt);
            }
        });

        txtsanghname.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N
        txtsanghname.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel2.setText("ID :");

        txtid.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel3.setText("एम. टी. दिनांक :");

        dtpmtdate.setFocusable(false);
        dtpmtdate.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel4.setText("बिल दिनांक पासून :");

        dtpfromdate.setFocusable(false);
        dtpfromdate.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        dtptodate.setFocusable(false);
        dtptodate.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel5.setText("ते");

        jLabel13.setBackground(new java.awt.Color(255, 255, 51));
        jLabel13.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("बँक तपशील");
        jLabel13.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("रक्कम काढली :");

        txtcurrentbankbalance.setEditable(false);
        txtcurrentbankbalance.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtcurrentbankbalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtcurrentbankbalance.setText("0.0");

        txtbankwithdrawamt.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtbankwithdrawamt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtbankwithdrawamt.setText("0.0");
        txtbankwithdrawamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbankwithdrawamtActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("बँकेत शिल्लक :");

        jLabel16.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("बँकेत सध्याची शिल्लक :");

        txtbankbalance.setEditable(false);
        txtbankbalance.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtbankbalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtbankbalance.setText("0.0");

        dtpbankwidhrawdate.setFocusable(false);
        dtpbankwidhrawdate.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("बँकेतून काढले दिनांक :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbankbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbankwithdrawamt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcurrentbankbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(dtpbankwidhrawdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcurrentbankbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpbankwidhrawdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbankwithdrawamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbankbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setBackground(new java.awt.Color(255, 255, 51));
        jLabel17.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("बिल तपशील");
        jLabel17.setOpaque(true);

        jLabel18.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel18.setText("एकूण दुध पुरवठा :");

        txttotalmilksend.setEditable(false);
        txttotalmilksend.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txttotalmilksend.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotalmilksend.setText("0.0");

        txttotalmilksendamt.setEditable(false);
        txttotalmilksendamt.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txttotalmilksendamt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotalmilksendamt.setText("0.0");

        jLabel19.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel19.setText("एकूण दुध रक्कम :");

        jLabel20.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel20.setText("शेअर कपात :");

        txtsharededuct.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtsharededuct.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsharededuct.setText("0.0");
        txtsharededuct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsharedeductActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel21.setText("रिबेट कपात :");

        txttotalrebatededuct.setEditable(false);
        txttotalrebatededuct.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txttotalrebatededuct.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotalrebatededuct.setText("0.0");

        jLabel22.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel22.setText("इतर कपात :");

        txtotherdeduct.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtotherdeduct.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtotherdeduct.setText("0.0");
        txtotherdeduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotherdeductActionPerformed(evt);
            }
        });
        txtotherdeduct.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtotherdeductPropertyChange(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel23.setText("एकूण रक्कम :");

        txttotalamountrecived.setEditable(false);
        txttotalamountrecived.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txttotalamountrecived.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotalamountrecived.setText("0.0");

        txttotalcommisiion.setEditable(false);
        txttotalcommisiion.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txttotalcommisiion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotalcommisiion.setText("0.0");

        jLabel31.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel31.setText("ओव्हर हेड रक्कम :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotalcommisiion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotalmilksendamt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotalmilksend, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttotalamountrecived, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtotherdeduct, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttotalrebatededuct, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsharededuct, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txttotalmilksend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txttotalmilksendamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txttotalcommisiion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtsharededuct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txttotalrebatededuct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtotherdeduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txttotalamountrecived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel24.setBackground(new java.awt.Color(255, 255, 51));
        jLabel24.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("कॅश तपशील");
        jLabel24.setOpaque(true);

        jLabel25.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel25.setText("अनामत घेणे :");

        txtanamatrecieved.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtanamatrecieved.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtanamatrecieved.setText("0.0");
        txtanamatrecieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanamatrecievedActionPerformed(evt);
            }
        });

        txtpaymentdetail.setEditable(false);
        txtpaymentdetail.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtpaymentdetail.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpaymentdetail.setText("0.0");

        jLabel26.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel26.setText("पगार वाटप :");

        jLabel27.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel27.setText("अनामत देणे :");

        txtanamatpaid.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtanamatpaid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtanamatpaid.setText("0.0");
        txtanamatpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanamatpaidActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel28.setText("डेअरी खर्च :");

        txtexpences.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtexpences.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtexpences.setText("0.0");
        txtexpences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexpencesActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel29.setText("हातावरील शिल्लक :");

        txtcashinhand.setEditable(false);
        txtcashinhand.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtcashinhand.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtcashinhand.setText("0.0");

        jLabel30.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel30.setText("नफा / तोटा :");

        txtprofitloss.setEditable(false);
        txtprofitloss.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtprofitloss.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtprofitloss.setText("0.0");

        jLabel33.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        jLabel33.setText("बचत :");

        txtbachat.setEditable(false);
        txtbachat.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N
        txtbachat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtbachat.setText("0.0");
        txtbachat.setFocusable(false);
        txtbachat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbachatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbachat, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtprofitloss, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcashinhand, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtexpences, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtanamatpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpaymentdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtanamatrecieved, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtanamatrecieved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtpaymentdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtbachat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtanamatpaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtexpences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtcashinhand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtprofitloss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel1)
                                        .addGap(9, 9, 9)
                                        .addComponent(txtsanghid, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dtpmtdate, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                                .addComponent(txtid)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(dtpfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtptodate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsanghname, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(dtpmtdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtpfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtptodate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtsanghid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsanghname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        framemode = 1;
        ED_BUTTONS(true, false);
        clearscreen();
        txtsanghid.requestFocus();
        getbankopnbal();
        this.date = new Date();

        dtpmtdate.setDate(date);
        dtpfromdate.setDate(date);
        dtptodate.setDate(date);
        dtpbankwidhrawdate.setDate(date);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        framemode = 2;
        ED_BUTTONS(true, false);
        txtsanghid.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void getbankbal() {
        if (!txtcurrentbankbalance.getText().equals("") || !txtbankwithdrawamt.getText().equals("")) {
            double netpaymentrecieved = 0;
            netpaymentrecieved = Double.parseDouble(txtcurrentbankbalance.getText()) - Double.parseDouble(txtbankwithdrawamt.getText());
            txtbankbalance.setText(""+twodf.format(netpaymentrecieved));
        }        
    }
    
    private void getbankopnbal() {
        try {
            String bankqry = "SELECT moneytransfer.bankbalance, moneytransfer.mtdate" +
                " FROM moneytransfer" +
                " WHERE (((moneytransfer.mtdate)<=#"+ mdy.format(dtptodate.getDate()) +"#))" +
                " ORDER BY moneytransfer.mtdate DESC;";
//            System.out.println(bankqry);
            try (PreparedStatement bankopbal = conn.prepareStatement(bankqry); ResultSet rs_bankopbal = bankopbal.executeQuery()) {
                if(rs_bankopbal.next()) {
                    double bankbal = rs_bankopbal.getDouble("bankbalance");
//                    System.out.println(bankbal);
                    bankbal = bankbal + Double.parseDouble(txttotalamountrecived.getText());
                    txtcurrentbankbalance.setText(""+twodf.format(bankbal));
                } else {
                    txtcurrentbankbalance.setText(""+twodf.format(methods.bankopbal + Double.parseDouble(txttotalamountrecived.getText())));
                }
            }
            getbankbal();
        } catch (SQLException ex) {
            Logger.getLogger(moneytransfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String msg = "रेकॉर्ड कायमचा काढून टाकणे?";
        int ans;
        if(!txtid.getText().equals("")) {
            ans = JOptionPane.showConfirmDialog(null, msg, title, JOptionPane.ERROR_MESSAGE);
            if(ans == JOptionPane.YES_OPTION){
                try {
                    String deleteqry = "DELETE * FROM moneytransfer WHERE ID = " + txtid.getText()+";";
                    PreparedStatement DELETE_QRY = conn.prepareStatement(deleteqry);
                    DELETE_QRY.execute();
                    JOptionPane.showMessageDialog(null, "रेकॉर्ड काढून टाकण्यात आला आहे.", title, JOptionPane.INFORMATION_MESSAGE);
                    clearscreen();
                    //displayrecord(4);
                } catch (SQLException ex) {
                    Logger.getLogger(sangh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "रेकॉर्ड नाही..!!", title, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // Insert new Record
            if(framemode==1){
                INSERT_QRY.setString(1, ""+dmy.format(dtpmtdate.getDate()));
                INSERT_QRY.setString(2, ""+dmy.format(dtpfromdate.getDate()));
                INSERT_QRY.setString(3, ""+dmy.format(dtptodate.getDate()));
                INSERT_QRY.setInt(4, Integer.parseInt(txtsanghid.getText()));
                INSERT_QRY.setDouble(5, Double.parseDouble(txttotalmilksend.getText()));
                INSERT_QRY.setDouble(6, Double.parseDouble(txttotalmilksendamt.getText()));
                INSERT_QRY.setDouble(7, Double.parseDouble(txtsharededuct.getText()));
                INSERT_QRY.setDouble(8, Double.parseDouble(txttotalrebatededuct.getText()));
                INSERT_QRY.setDouble(9, Double.parseDouble(txtotherdeduct.getText()));
                INSERT_QRY.setDouble(10, Double.parseDouble(txttotalamountrecived.getText()));
                INSERT_QRY.setDouble(11, Double.parseDouble(txtcurrentbankbalance.getText()));
                INSERT_QRY.setDouble(12, Double.parseDouble(txtbankwithdrawamt.getText()));
                INSERT_QRY.setDouble(13, Double.parseDouble(txtbankbalance.getText()));
                INSERT_QRY.setDouble(14, Double.parseDouble(txtanamatrecieved.getText()));
                INSERT_QRY.setDouble(15, Double.parseDouble(txtpaymentdetail.getText()));
                INSERT_QRY.setDouble(16, Double.parseDouble(txtanamatpaid.getText()));
                INSERT_QRY.setDouble(17, Double.parseDouble(txtexpences.getText()));
                INSERT_QRY.setDouble(18, Double.parseDouble(txtcashinhand.getText()));
                INSERT_QRY.setDouble(19, Double.parseDouble(txtprofitloss.getText()));
                INSERT_QRY.setDouble(20, Double.parseDouble(txttotalcommisiion.getText()));
                INSERT_QRY.setString(21, ""+dmy.format(dtpbankwidhrawdate.getDate()));
                INSERT_QRY.setDouble(22, Double.parseDouble(txtbachat.getText()));

                INSERT_QRY.execute();
            }
            // Update Existing record
            if(framemode==2){
//                String updateqry = "UPDATE moneytransfer SET sname = ?, address = ?,"
//                + " cno = ?, rtc_no = ?, comission = ?,"
//                + " rebate = ?, shareanamat = ?"
//                + " WHERE ID = "+txtsanghid.getText()+";";
//                PreparedStatement UPDATE_QRY = conn.prepareStatement(updateqry);
//                UPDATE_QRY.setString(1, txtsanghname.getText().toString());
//                UPDATE_QRY.setString(2, txtaddress.getText());
//                UPDATE_QRY.setString(3, txtcontacno.getText());
//                UPDATE_QRY.setInt(4, Integer.parseInt(""+cmbratechart.getSelectedItem()));
//                UPDATE_QRY.setDouble(5, Double.parseDouble(txtcommision.getText()));
//                UPDATE_QRY.setDouble(6, Double.parseDouble(txtrebate.getText()));
//                UPDATE_QRY.setDouble(7, Double.parseDouble(txtshareanamat.getText()));
//
//                UPDATE_QRY.execute();
            }
            String msg = "रेकॉर्ड सेव्ह झाला.";
            JOptionPane.showMessageDialog(null, msg, title, JOptionPane.INFORMATION_MESSAGE);
            framemode=3;
            ED_BUTTONS(false, true);
            displayrecord(4);
        } catch (SQLException ex) {
            Logger.getLogger(sangh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        displayrecord(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(framemode==3){
            if (conn!=null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(moneytransfer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            dispose();
        }
        else {
            framemode = 3;
            ED_BUTTONS(false, true);
            displayrecord(4);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
//        try {
//            methods.displayreport("Producerlist", conn);
//        } catch (SQLException ex) { //JRException |
//            Logger.getLogger(sangh.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(1);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(2);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(3);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().equals("")){
            displayrecord(4);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtsanghidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsanghidKeyReleased
        if(evt.getKeyCode()==10){
        }
    }//GEN-LAST:event_txtsanghidKeyReleased

    private void txtotherdeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotherdeductActionPerformed
        gettotalpaymentrecieved();
    }//GEN-LAST:event_txtotherdeductActionPerformed

    private void txtotherdeductPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtotherdeductPropertyChange
        
    }//GEN-LAST:event_txtotherdeductPropertyChange

    private void txtbankwithdrawamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbankwithdrawamtActionPerformed
        getbankbal();
        getcashinhandprofitloss();
    }//GEN-LAST:event_txtbankwithdrawamtActionPerformed

    private void txtanamatrecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanamatrecievedActionPerformed
        getcashinhandprofitloss();
    }//GEN-LAST:event_txtanamatrecievedActionPerformed

    private void txtanamatpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanamatpaidActionPerformed
        getcashinhandprofitloss();
    }//GEN-LAST:event_txtanamatpaidActionPerformed

    private void txtexpencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexpencesActionPerformed
        getcashinhandprofitloss();
    }//GEN-LAST:event_txtexpencesActionPerformed

    private void txtsanghidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsanghidActionPerformed
            if(!txtsanghid.getText().equals("")) {
                int pid = Integer.parseInt(txtsanghid.getText());
                String pname;
                double disp_qty;
                double disp_amt;
                double share_amt;
                double comm_amt;
                double rebate_amt;
                
                double payment_amt = 0;
                double shetkari_bachat = 0;
                
                try {
                    pname = getprodname(pid);
                    txtsanghname.setText(pname);
                    if(!pname.equals("")) {
                        // Get dispatch detail
                        
                        String qry_dispatch = "SELECT Sum(milkdispatch.qty2) AS SumOfqty2, Sum(milkdispatch.amt2)"+
                            " AS SumOfamt2, Sum((([milkdispatch]![amt2]*[sangh]![shareanamat])/100)) AS shareamt,"+
                            " Sum(([milkdispatch]![qty2]*[sangh]![comission])) AS commission,"+
                            " Sum(([milkdispatch]![qty2]*[sangh]![rebate])) AS rebateamt, Sum([milkdispatch]![qty3]) AS sumofqty3, " +
                            " Sum([milkdispatch]![amt3]) AS sumofamt3 FROM sangh INNER JOIN milkdispatch ON sangh.ID = milkdispatch.scode" +
                            " WHERE (((milkdispatch.disp_datetime)>=#"+ mdy.format(dtpfromdate.getDate()) +"#) AND"+
                            " ((milkdispatch.disp_datetime)<=#"+ mdy.format(dtptodate.getDate()) +"#) AND"+
                            " ((milkdispatch.scode)="+ txtsanghid.getText() +"));";
//                        System.out.println(qry_dispatch);
                        try (PreparedStatement dispatch_detail = conn.prepareStatement(qry_dispatch);ResultSet rs_dispatch = dispatch_detail.executeQuery()) {
                            while(rs_dispatch.next()) {
                                disp_qty = rs_dispatch.getDouble("SumOfqty2") + rs_dispatch.getDouble("SumOfqty3");
                                disp_amt = rs_dispatch.getDouble("SumOfamt2") + rs_dispatch.getDouble("SumOfamt3");
                                share_amt = rs_dispatch.getDouble("shareamt");
                                comm_amt = rs_dispatch.getDouble("commission");
                                rebate_amt = rs_dispatch.getDouble("rebateamt");
                                
                                txttotalmilksend.setText(""+twodf.format(disp_qty));
                                txttotalmilksendamt.setText(""+twodf.format(disp_amt));
                                txttotalcommisiion.setText(""+twodf.format(comm_amt));
                                txtsharededuct.setText(""+twodf.format(share_amt));
                                txttotalrebatededuct.setText(""+twodf.format(rebate_amt));
                                
                                gettotalpaymentrecieved();
                                getbankopnbal();
                            }
                        }
                        qry_dispatch = "";
                        
                        qry_dispatch = "SELECT Sum(milkCollectionBill.amt_payable) AS SumOfamt_payable," +
                            "Sum(milkCollectionBill.tot_ribet) AS SumOftot_ribet " +
                            " FROM milkCollectionBill" +
                            " WHERE (((milkCollectionBill.from_date)>=#"+ mdy.format(dtpfromdate.getDate()) +"#)"+
                            " AND ((milkCollectionBill.to_date)<=#"+ mdy.format(dtptodate.getDate()) +"#));";
                        try (PreparedStatement getpaymamt = conn.prepareStatement(qry_dispatch); ResultSet rs_pay = getpaymamt.executeQuery()) {
                            while(rs_pay.next()) {
                                payment_amt = rs_pay.getDouble("SumOfamt_payable");
                                shetkari_bachat = rs_pay.getDouble("SumOftot_ribet");
                            }
                            if (payment_amt==0) {
                                JOptionPane.showMessageDialog(null, "कृपया बिल तयार करा..!!","Milkman", JOptionPane.ERROR_MESSAGE);
                            }
                            txtpaymentdetail.setText(""+twodf.format(payment_amt));
                            txtbachat.setText(""+twodf.format(shetkari_bachat));
                        }
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "कृपया संघ कोड तपासा..!!","Milkman", JOptionPane.ERROR_MESSAGE);
                        txtsanghid.requestFocus();
                        txtsanghid.setText(null);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "कृपया संघ कोड तपासा..!!","Milkman", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(milkdispatch.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex,"Milkman", JOptionPane.ERROR_MESSAGE);
                }
            }

    }//GEN-LAST:event_txtsanghidActionPerformed

    private void txtbachatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbachatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbachatActionPerformed

    private void txtsharedeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsharedeductActionPerformed
        gettotalpaymentrecieved();
    }//GEN-LAST:event_txtsharedeductActionPerformed

    private void getcashinhandprofitloss() {
        if(!"".equals(txtbankwithdrawamt) || !"".equals(txtanamatrecieved) || !"".equals(txtanamatpaid) || !"".equals(txtexpences)) {
            Double CIH = (Double.parseDouble(txtbankwithdrawamt.getText()) + Double.parseDouble(txtanamatrecieved.getText())) 
                    - (Double.parseDouble(txtpaymentdetail.getText()) + Double.parseDouble(txtexpences.getText()) + Double.parseDouble(txtanamatpaid.getText()));
            txtcashinhand.setText(""+twodf.format(CIH));
            
            Double PL = Double.parseDouble(txttotalamountrecived.getText()) - (Double.parseDouble(txtanamatrecieved.getText()) + 
                    Double.parseDouble(txtpaymentdetail.getText()) + Double.parseDouble(txtanamatpaid.getText()) + 
                    Double.parseDouble(txtexpences.getText()));
            txtprofitloss.setText(""+twodf.format(PL));
        }
    }
    
    private void gettotalpaymentrecieved() {
        if (!"".equals(txttotalmilksendamt.getText()) || !"".equals(txttotalcommisiion.getText()) || !"".equals(txtsharededuct.getText())) {
            double netpaymentrecieved = 0;
            netpaymentrecieved = (Double.parseDouble(txttotalmilksendamt.getText()) + Double.parseDouble(txttotalcommisiion.getText()))
                    - (Double.parseDouble(txtsharededuct.getText()) + Double.parseDouble(txttotalrebatededuct.getText()) + Double.parseDouble(txtotherdeduct.getText()));
            txttotalamountrecived.setText(""+twodf.format(netpaymentrecieved));
            
            getbankopnbal();
        }
    }
    
    private String getprodname(int id) throws SQLException {
        String pname = "";
        String qry2 = "SELECT sangh.sname, sangh.rtc_no, sangh.ID" +
                " FROM sangh" +
                " WHERE (((sangh.ID)="+id+"));";
        PreparedStatement prname = conn.prepareStatement(qry2);
        ResultSet rspname;
        rspname = prname.executeQuery();
        while(rspname.next()) {
            pname = rspname.getString("sname");
            prod_ratechartno = rspname.getInt("rtc_no");
            if(!pname.equals("")) {
                // do nothing return pname
            } else {
                pname = "";
            }
        }
        rspname.close();
        return pname;
    }
    
    private void displayrecord(int flag) {
        if(framemode == 3){
            try {
                qry = null;
                if(flag==4){
                   qry = "SELECT * FROM moneytransfer WHERE ID=(SELECT max(ID) FROM moneytransfer);";
                }
                if(flag==1){
                   qry = "SELECT * FROM moneytransfer WHERE ID=(SELECT min(ID) FROM moneytransfer);";
                }
                if(flag==2){
                   qry = "SELECT * FROM moneytransfer WHERE ID<"+txtid.getText()+" ORDER BY ID DESC;";
                }
                if(flag==3){
                   qry = "SELECT * FROM moneytransfer WHERE ID>"+txtid.getText()+" ORDER BY ID;";
                }                
                if(flag==5){
                   qry = "SELECT * FROM moneytransfer WHERE ID="+txtid.getText()+" ORDER BY ID;";
                }                                
                PreparedStatement selectqry = conn.prepareStatement(qry);
                ResultSet rs = selectqry.executeQuery();
                
                while(rs.next()){
                    clearscreen();
                    txtid.setText(rs.getString("ID"));
                    dtpmtdate.setDate(rs.getDate("mtdate"));
                    dtpfromdate.setDate(rs.getDate("fromdate"));
                    dtptodate.setDate(rs.getDate("todate"));
                    txtsanghid.setText(""+rs.getInt("snaghcode"));
                    txttotalmilksend.setText(""+twodf.format(rs.getDouble("totalmilksend")));
                    txttotalmilksendamt.setText(""+twodf.format(rs.getDouble("totalmilkamt")));
                    txtsharededuct.setText(""+twodf.format(rs.getDouble("sharededuct")));
                    txttotalrebatededuct.setText(""+twodf.format(rs.getDouble("rebatededuct")));
                    txtotherdeduct.setText(""+twodf.format(rs.getDouble("otherdeduct")));
                    txttotalamountrecived.setText(""+twodf.format(rs.getDouble("totalamtrecieved")));
                    txtcurrentbankbalance.setText(""+twodf.format(rs.getDouble("bankcurrentbal")));
                    txtbankwithdrawamt.setText(""+twodf.format(rs.getDouble("bankwithdrawamt")));
                    txtbankbalance.setText(""+twodf.format(rs.getDouble("bankbalance")));
                    txtanamatrecieved.setText(""+twodf.format(rs.getDouble("anamatrecieved")));
                    txtpaymentdetail.setText(""+twodf.format(rs.getDouble("netpayment")));
                    txtanamatpaid.setText(""+twodf.format(rs.getDouble("anamatpaid")));
                    txtexpences.setText(""+twodf.format(rs.getDouble("totalexpences")));
                    txtcashinhand.setText(""+twodf.format(rs.getDouble("cashinhand")));
                    txtprofitloss.setText(""+twodf.format(rs.getDouble("profitorloss")));
                    txtbachat.setText(""+twodf.format(rs.getDouble("shetkaribachat")));
                    dtpbankwidhrawdate.setDate(rs.getDate("banckwidhrawdate"));
                    
                    break;
                }
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(moneytransfer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprint;
    private com.toedter.calendar.JDateChooser dtpbankwidhrawdate;
    private com.toedter.calendar.JDateChooser dtpfromdate;
    private com.toedter.calendar.JDateChooser dtpmtdate;
    private com.toedter.calendar.JDateChooser dtptodate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtanamatpaid;
    private javax.swing.JTextField txtanamatrecieved;
    private javax.swing.JTextField txtbachat;
    private javax.swing.JTextField txtbankbalance;
    private javax.swing.JTextField txtbankwithdrawamt;
    private javax.swing.JTextField txtcashinhand;
    private javax.swing.JTextField txtcurrentbankbalance;
    private javax.swing.JTextField txtexpences;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtotherdeduct;
    private javax.swing.JTextField txtpaymentdetail;
    private javax.swing.JTextField txtprofitloss;
    private javax.swing.JTextField txtsanghid;
    private javax.swing.JTextField txtsanghname;
    private javax.swing.JTextField txtsharededuct;
    private javax.swing.JTextField txttotalamountrecived;
    private javax.swing.JTextField txttotalcommisiion;
    private javax.swing.JTextField txttotalmilksend;
    private javax.swing.JTextField txttotalmilksendamt;
    private javax.swing.JTextField txttotalrebatededuct;
    // End of variables declaration//GEN-END:variables
}
