/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package milkman;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.hpsf.Variant;
/**
 *
 * @author Rakesh
 */
public class pigmyinterface extends javax.swing.JInternalFrame {

    /**
     * Creates new form pigmyinterface
     */
    
    private int[] grid;
    private Connection conn;
    private ResultSet rs;
    SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss a");
    
    public pigmyinterface() {
        try {
            initComponents();
            dtpfromdate.setDate(methods.currdate);
            dtptodate.setDate(methods.currdate);
            
            cmbprodgroup.removeAllItems();
            int i=0;
                
                if(conn!=null) {
                    conn.close();
                }
                conn = methods.getConnection();
                ResultSet rscombo;
                String qry;
                qry = "";
                
                // producer group
                qry = "SELECT producergroup.ID, producergroup.grname\n" +
                        "FROM producergroup\n" +
                        "ORDER BY producergroup.ID;";
                PreparedStatement loadqry = conn.prepareStatement(qry);
                rscombo = loadqry.executeQuery();
                grid = new int[30];
                while(rscombo.next()) {
                   cmbprodgroup.insertItemAt(rscombo.getString("grname"), i);
                   grid[i] = rscombo.getInt("ID");
                   i++;        
                }
                rscombo.close();
                cmbprodgroup.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(pigmyinterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dtpfromdate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        dtptodate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cmbprodgroup = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(113, 168, 168));

        jLabel5.setFont(new java.awt.Font("Mangal", 1, 24)); // NOI18N
        jLabel5.setText("पिग्मी इंटेरफेस");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(483, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("तारखे पासून :");

        dtpfromdate.setFocusable(false);
        dtpfromdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel8.setText("ते");

        dtptodate.setFocusable(false);
        dtptodate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("उत्पादक ग्रुप :");

        cmbprodgroup.setFont(new java.awt.Font("Mangal", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(113, 168, 168));

        jButton1.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jButton1.setText("डाटा इम्पोर्ट करणे");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jButton2.setText("बाहेर");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Mangal", 1, 18)); // NOI18N
        jLabel9.setText("फाईल :");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton3.setText("Select File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dtpfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(dtptodate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmbprodgroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dtpfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(dtptodate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbprodgroup))
                    .addGap(125, 125, 125)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BufferedReader reader = null;
        try {
            SimpleDateFormat dmy = new SimpleDateFormat("dd/MM/yyyy");
            String str;
            Variant values[];
            int i;
            int p_code = 0;
            String enrtrydate = null;
            int prodgrid = 0;
            int mlktype = 0;
            int shft = 0;
            int sno = 0;
            ResultSet rsprod;
            double ltr =0.0;
            double rate = 0.0;
            double amt =0.0;
            double snf =0.0;
            double fat =0.0;
            double clr =0.0;
            sno=0;
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(jTextField1.getText())));
            String line = null;
            String newline = null;
            int lno = 1;
            String[] feilds;
            while((line = reader.readLine()) != null) {
                newline = line.trim();
                //newline = newline.replaceAll("\\s+"," ");
                //newline = newline.replaceAll("\\n+","");
                //newline = newline.replaceAll("=",".");
                System.out.println("Line No = "+lno);
                feilds = newline.split(",");
                
                System.out.println(newline);
                System.out.println("Length : " + newline.length());
                int fid = 0;
                
                if (newline.length() > 0 && newline.length() <= 7) {
//                    if ("Id".equals(feilds[0])) {
//                            System.out.println(feilds[0]);
//                            System.out.println(feilds[1]);
//                            System.out.println(feilds[2]);
//                        
//                        prodgrid = Integer.parseInt(feilds[2]);
//                    }
                } else if (newline.length() > 7 && newline.length() <= 18) {
//                    if ("DATE:".equals(feilds[0])) {
//                        sno = 0;
//                            System.out.println(feilds[0]);
//                            System.out.println(feilds[1]);
//                            //System.out.println(feilds[2]);
//                        
//                        enrtrydate = feilds[1];
//                     
//                    }
//                    if (feilds[0].equals("SESSION:")) {
////                            System.out.println(feilds[0]);
////                            System.out.println(feilds[1]);
//                            //System.out.println(feilds[2]);
//                        
////                        System.out.println("Shift : "+feilds[1]);
//                        if (feilds[1].equals("MORNING")) {
//                            shft=1;
//                        } else {
//                            shft=2;
//                        }                    
//                    }
                } else if (newline.length() > 18 && newline.length() <= 50) {
                            
//                    sno = sno + 1;
//                    p_code = Integer.parseInt(feilds[0]);
//                    if("B".equals(feilds[2])) {
//                        mlktype = 1;
//                    } else {
//                        mlktype = 2;
//                    }
//                    enrtrydate = feilds[4];
//                    ltr = Double.parseDouble(feilds[2]);
//                    fat = Double.parseDouble(feilds[3]);
//                    snf = Double.parseDouble(feilds[4]);
//                    rate = Double.parseDouble(feilds[5]);
//                    amt = Double.parseDouble(feilds[6]);                            
//
//                    // insert record 
//                    String qry = "INSERT INTO mlkCollection (trn_date, shift_id, prod_code," +
//                    " sample_no, mlkType_id, weight, fat, degree, snf, rate," +
//                    " prodgrid,prod_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
//                    PreparedStatement INSERT_QRY;
//                    INSERT_QRY = conn.prepareStatement(qry);
//
//                    INSERT_QRY.setString(1, enrtrydate); //""+sdf2.format(enrtrydate
//                    INSERT_QRY.setInt(2, shft);
//                    INSERT_QRY.setInt(3, p_code);
//                    INSERT_QRY.setInt(4, sno);
//                    INSERT_QRY.setInt(5, mlktype);
//                    INSERT_QRY.setDouble(6, ltr);
//                    INSERT_QRY.setDouble(7, fat);
//                    INSERT_QRY.setDouble(8, 0);
//                    INSERT_QRY.setDouble(9, snf);
//                    INSERT_QRY.setDouble(10, rate);
//                    INSERT_QRY.setInt(11, prodgrid);
//
//                    //get prod_id
//                    String qry2 = "SELECT producer.prod_id " +
//                            "FROM producer " +
//                            "WHERE (((producer.ID)="+p_code+") AND ((producer.producergroupid)="+prodgrid+"));";
//                    PreparedStatement stmt = conn.prepareStatement(qry2);
//                    int pro_id = 0;// = stmt.execute;
//                    ResultSet rsprodid = stmt.executeQuery();
//                    if (rsprodid.next()) {
//                        pro_id = rsprodid.getInt("prod_id");
//                    }
////                    System.out.println(qry2);
////                    System.out.println("Prod_ID" + pro_id);
//                    rsprodid.close();
//                    stmt.close();
//
//                    INSERT_QRY.setInt(12, pro_id);
//
//                    INSERT_QRY.execute();                    
//                    // end                                      
                } else if (newline.length() > 18 && newline.length() <= 110) {
                    
                    // fOR bALAJI mACHINE
                    prodgrid = grid[cmbprodgroup.getSelectedIndex()];
                    feilds = newline.split(",");
                    sno = sno + 1;
                    p_code = Integer.parseInt(feilds[7]);
                    System.out.println("Code : "+p_code);
                    if("C".equals(feilds[2])) {
                        mlktype = 1;
                    } else {
                        mlktype = 2;
                    }
                    if("M".equals(feilds[6])) {
                        shft = 1;
                    } else {
                        shft = 2;
                    }
                    System.out.println(" Shift: "+shft);
                    enrtrydate = feilds[4];
                    String[] newdate = enrtrydate.split("/");
                    String ndate = newdate[0] + "/" + newdate[1] + "/20" + newdate[2];
                    Date new_date = dmy.parse(ndate);

                    
                    System.out.println(" Date: "+dmy.format(new_date));
                    System.out.println(" Milk: "+mlktype);
                    ltr = Double.parseDouble(feilds[8]);
                    System.out.println(" ltr: "+ltr);
                    fat = Double.parseDouble(feilds[9]);
                    System.out.println(" Fat: "+fat);
                    clr = Double.parseDouble(feilds[10]);
                    System.out.println(" clr: "+clr);
                    snf = Double.parseDouble(feilds[11]);
                    System.out.println(" snf: "+snf);
                    rate = Double.parseDouble(feilds[15]);
                    System.out.println(" rate: "+rate);
                    amt = Double.parseDouble(feilds[17]);                            
                    System.out.println(" amt: "+amt);

                    // insert record 
                    String qry = "INSERT INTO mlkCollection (trn_date, shift_id, prod_code," +
                    " sample_no, mlkType_id, weight, fat, degree, snf, rate," +
                    " prodgrid,prod_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement INSERT_QRY;
                    INSERT_QRY = conn.prepareStatement(qry);

                    INSERT_QRY.setString(1, ""+dmy.format(new_date)); //""+sdf2.format(enrtrydate
                    INSERT_QRY.setInt(2, shft);
                    INSERT_QRY.setInt(3, p_code);
                    INSERT_QRY.setInt(4, sno);
                    INSERT_QRY.setInt(5, mlktype);
                    INSERT_QRY.setDouble(6, ltr);
                    INSERT_QRY.setDouble(7, fat);
                    INSERT_QRY.setDouble(8, clr);
                    INSERT_QRY.setDouble(9, snf);
                    INSERT_QRY.setDouble(10, rate);
                    INSERT_QRY.setInt(11, prodgrid); //prodgrid

                    //get prod_id
                    String qry2 = "SELECT producer.prod_id " +
                            "FROM producer " +
                            "WHERE (((producer.ID)="+p_code+") AND ((producer.producergroupid)="+prodgrid+"));";
                    int pro_id;
                    try (PreparedStatement stmt = conn.prepareStatement(qry2)) {
                        pro_id = 0;
                        try (ResultSet rsprodid = stmt.executeQuery()) {
                            if (rsprodid.next()) {
                                pro_id = rsprodid.getInt("prod_id");
                            }
                            System.out.println(" prod_id:: "+pro_id);
                        }
                    }

                    INSERT_QRY.setInt(12, pro_id);

                    INSERT_QRY.execute();                    
                    // end                    
                }
                
                lno = lno + 1;
            }
            JOptionPane.showMessageDialog(null, "रेकॉर्ड सेव्ह झाला...!!!", title, JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(pigmyinterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | SQLException ex) {
            Logger.getLogger(pigmyinterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pigmyinterface.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                Logger.getLogger(pigmyinterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(null);
        //File f = jfc.getSelectedFile();
        File f = jfc.getSelectedFile();
        String fp = f.getAbsolutePath();
        jTextField1.setText(fp);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbprodgroup;
    private com.toedter.calendar.JDateChooser dtpfromdate;
    private com.toedter.calendar.JDateChooser dtptodate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
